5 goal object
kmc-jp/puzzleGame2023 pull request #40
Opened 2023-07-05 09:40 UTC by OsawaKousei

やったこと
・ゴールエリア作成
7d627b36568a6dc7eebf9f80e0c3b9522b18a133
・ゴールエリアに描いたオブジェクトが入ったことを判定
3037a716cbe9cadb29bf1a9b322324b23755ee95
・テスト用にspaceを押すと描いたオブジェクトが動く機能
f9a05cc26fb773e8cf8e63211b6559e277e485a8
・描いたオブジェクトがゴールエリアにあるとHPが減少
　　・ただし、1度HPが減ると無敵時間に入り、その間はダメージを受けない
4da4fdcdc3c74e8adb5a5501df7436841102af59
・侵入不可エリアの設定
6ea1c78eefcadce3ab11aa17f8811e5d584895ff
・簡易的な勝利判定
c590a93322bae1da2aec822d2f2bc0bc3fc0a6ca

コードの説明
・ゴールエリア、侵入不可エリアの枠線はGMで作っています
・ゴールエリアにオブジェクトが入った判定はLineObjectMを描いた各オブジェクトにアタッチして、そこで判定しています
・spaceを押すとオブジェクトが動く機能もLineObjectMで実装しています
・HPはGMがゴールエリア侵入判定を受け取って、GMで管理しています
・勝敗判定はGMで行っています

レビューよろしくお願いします

2023-07-11 15:22 UTC, Zudies requested changes
機能的には大丈夫ですが、プログラマーとして調整したところはかなりあります。

せっかくプールリクエストを作ってくれたとはいえ、もうちょっとコードの構成を考えてください。例外も結構あるけれど、「一つ関数に一つ機能」のはプログラミングの基本です。
手数をおかけしますがよろしくお願いします。

2023-07-11 15:22 UTC, Zudies commented on Assets/Scripts/GMforTest01.cs
> +        lineObj.transform.SetParent(transform);
コメントはいいというものの、これはちょっとやりすぎ気がします。簡単なコードの場合（`lineObj.name = name`）、コメントを入れなくても問題ありません。そのコードを見たらすぐに分かりますから。

この場合は、上に`//新しオブジェクトの初期化`などの一つコメントだけで十分だと思います。

2023-07-11 15:22 UTC, Zudies commented on Assets/Scripts/GMforTest01.cs
> +    }
最初に書いていたやつと同じく、これを別のオブジェクトに移動してください。

そして、このような機能は普通ならば、手動的に計算するではなくて、新しいオブジェクト（Goalオブジェクト）を作って、そのオブジェクトにColliderを付けて、そのColliderに他のオブジェクト（例えば作成した描写のオブジェクト）にぶつかったら、適切な処理を行うのが基本です。

具体的な例が欲しければ、気軽に聞いてください。

2023-07-14 11:39 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
> +    public int drawFrag;
了解です。修正しました
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/e670e6837883f14f98b774139f50d91072d01c76

2023-07-14 11:46 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
> +    //インクの最大量(秒)
了解です。修正しました。
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/8bcc5d273cef3c5f9be60c3c625f124ad672b44b

2023-07-14 12:40 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
>          if (! Input.GetMouseButton(0) && _inkLeft <= 2)
了解です。修正しました。
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/f91171f2850ffaddb4c6f961e6c22f29df83c248

2023-07-14 12:42 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
> +        lineObj.transform.SetParent(transform);
了解です。修正しました。
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/dd43951a5a25575824f20295f9c9ac387f454b03

2023-07-15 06:12 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
> +    }
ステージ初期化機能を別オブジェクトに移動しました。
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/490c85cf9528f46bcf4c31365f871875045e9de2
衝突判定方法は変わってません

2023-07-15 06:35 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
> +    public int HP;
了解です。修正しました。
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/08e6a405031cd09466caad6dfb4a2f987de2e68e

2023-07-15 06:35 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
> +    public int godModeFrag = 0;
このコミットで同時に修正しました。
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/08e6a405031cd09466caad6dfb4a2f987de2e68e

2023-07-15 06:35 UTC, OsawaKousei commented on Assets/Scripts/GMforTest01.cs
> +    //勝敗判定用
このコミットで同時に修正しました。
https://github.com/kmc-jp/puzzleGame2023/pull/40/commits/08e6a405031cd09466caad6dfb4a2f987de2e68e

2023-08-06 12:05 UTC, Zudies commented
37-basic-game-data-componentから実質マージしましたよね。
今回は大丈夫ですが、これからgitのmergeかcherry-pickの機能を使って必要なファイルやコミットを取ったほうが良いと思います。それを使わないとgitの視点からマージ元とマージ先のファイルが全く別のファイルにみられることがあるので、マージする時、同じファイルだとしてもconflictが出てしまいます。

2023-08-06 12:27 UTC, Zudies commented
コード的は大体修正しました。ありがとうございます。
ちょっとこだわりがある何ヵ所は残っていますが、それは後で（もうちょっとステージが実装した後）修正しても構いません。
conflictがあるからそれを修正したら私はUnityで機能を確認します。

2023-08-18 16:38 UTC, Zudies approved these changes

2023-08-18 16:40 UTC, merged