69 qualia intensity implementation
kmc-jp/puzzleGame2023 pull request #71
Opened 2023-09-04 12:12 UTC by LosenkaNiya

「クオリア強度」はゲーム内でアニマを描ける残量のことです。
UIに非依存な実装をするために、残量の増減を細かく指定する機能、及び残量に対してイベントを設定できるようにしました。
実装した機能は以下の通りです。
- 指定量だけ増やす、減らす機能(アイテムやデバフなどによってゲージが瞬間的に増減する時に使用)
- ゆっくりと回復、消耗する機能(同じくアイテムやデバフの使用を想定)
- 自動回復

"Qualia Intensity" is a remaining which shows the capacity of drawing animas.
To accomplish the implementation independent of UI, I implemented features to designate increase/decrease in detail and to enable programmers to subscribe event depending on the amount of remaining.
Features I implemented are below:
- Ability to increase or decrease by a specified amount (used when the gauge is momentarily increased or decreased by items, debuffs, etc.)
- A function that slowly recovers or depletes (also assumes the use of items or debuffs)
- Automatic recovery

2023-09-04 16:15 UTC, Zudies requested changes
スレッドで挑戦のを大歓迎します！この機能にスレッドを使うのはちょっと意味不明ですが…それはともかく、レビューしましょう！

2023-09-04 16:15 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +        int totalIncreaseCount = (int)(timeToReach * _updateTimesPerSecond);
計算ミス。amountまで増加されない可能性があります。
amount = 25.0f
timeToReach = 2.4f
_updateTimesPerSecond = 11
**totalIncreaseCount = 26 (26.4f -> int化 = 26)**
amountPerUpdate = 0.9469697f
IncreasePatternCheckedは26回呼び出されるため、増加量は合計26 * 0.9469697 = **24.6212**

2023-09-04 16:15 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +        int totalIncreaseCount = (int)(timeToReach * _updateTimesPerSecond);
ちなみに、増加が終わったら、最後にもう一回Task.Delayが呼び出されます。それはちょっともったいないと思っています。

2023-09-04 16:15 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            await Task.Delay(increaseInterval);
ただの確認です。
Task.Delay（Windowsの時間待ち系の関数もほぼ含めて）はちょっとだけ（数ms程度）ずれることがあります。これは大丈夫ですか？

2023-09-04 16:15 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            IncreasePatternChecked(amountPerUpdate, IntensityUpdatePattern.Continuous);
このループに入ったら、もう二度と戻れません。

2023-09-04 16:15 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +        _autoRecoveryCts.Cancel();
↑さっき言ったと同じく、EnableAutoRecoveryAsyncが始まったら、このctsでは止められません。

2023-09-04 16:20 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            IncreasePatternChecked(amountPerUpdate, IntensityUpdatePattern.Continuous);
言い忘れました。
ここはrace conditionになる恐れがあります。
IncreasePatternCheckedは別のスレッドに同じタイミングで呼び出されたら、_intensityの更新の競争になる可能性があります。
ほかのAsync関数も同じです。

2023-09-05 11:27 UTC, LosenkaNiya commented on Assets/Scripts/QualiaIntensity.cs
> +        _updateTimesPerSecond = 60;
クオリア強度はゲーム中で様々なコンポーネントに利用されることになると思います。
一例ですが、
- 視覚的なゲージアニメーション()
- 数値表示
- ゲージが回復した際のSEコントローラー

こういったコンポーネントがQualiaIntensityをメンバに持つことで、汎用的な実装ができると思ったので通常のクラスで実装しました。また、MonoBehaviourを継承していないためコルーチンを利用できないので、タスクを利用しました。

2023-09-05 11:28 UTC, LosenkaNiya commented on Assets/Scripts/QualiaIntensity.cs
> +        Discreate,
スペルミスですね、修正します。

2023-09-05 11:33 UTC, LosenkaNiya commented on Assets/Scripts/QualiaIntensity.cs
> +            await Task.Delay(increaseInterval);
それほど厳密でなくても問題ないと思うので、許容範囲です。

2023-09-05 14:14 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            return;
これはサイレント故障（？）です。
EnableAutoRecoveryはすでに有効の場合、二度目の呼び出しを無視してしまいます。
エラーをログするなり一番高いamountPerSecond価を使うなり、このエラーを何とか処理するべきです。

2023-09-05 14:29 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +        lock (null) {
`lock (null)`はNGな気がします。
普通は_intensityなどをlockするべきですが、lockはobjectのみを使えられるみたい。
このクラスは他に使えそうのメンバーがないなら、mutexとかを作ってみたらどうですか？

2023-09-05 14:31 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            throw;
`throw;`はもう一度このexceptionをスローします。

2023-09-05 14:34 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            lock (null) {
この中には共有リソースがないので、lockは必要がありません。

2023-09-05 14:40 UTC, LosenkaNiya commented on Assets/Scripts/QualiaIntensity.cs
> +            return;
サイレント故障という言葉はあっています。けれども、これは問題ないと思っています。
自動回復は同時に2つ以上有効になることはないです。
この機能は主に「アニマを描きだす時」にdisableして、「アニマを描き終わった時」にenableすることを想定して作ってます。

2023-09-05 14:45 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +    public void Dispose() {
このコード自体は問題ありませんが、ちょっと違和感を感じます。

disposeされたオブジェクトを使うのは基本的NGです。しかし、この関数は他のスレッドにキャンセルの通知を送るだけ、それらのスレッドを待たずに戻ります。そうすると、この関数が戻る時点、他のスレッドがまだ動いている（つまり、このオブジェクトがまだ使用されている）可能性があります。

2023-09-05 14:48 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            await IncreaseScheduledAsync(amount, timeToReach, updateScheduleCts.Token);
注意：awaitは自動的にスレッドを作ることがありません。IncreaseScheduledAsyncが戻るまでこの関数はずっとブロックしますよ。

2023-09-05 14:50 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +            return;
それなら、念のためDebug.Assertを使ってください。

2023-09-05 15:07 UTC, LosenkaNiya commented on Assets/Scripts/QualiaIntensity.cs
> +            await IncreaseScheduledAsync(amount, timeToReach, updateScheduleCts.Token);
IncreaseScheduledAsyncは途中でキャンセルされる可能性があります。もし、キャンセルされずに正常に終了した場合には、**終了するまで待機した後**キャンセルリストからremoveします。キャンセルされた場合には、Disposeがキャンセルリストをスキャンして(この場合は正常終了されていないので、リストにはトークンソースが残っている)キャンセルを発行します。

こういうことをやりたかったので、awaitでブロックしています。

2023-09-14 14:30 UTC, Zudies approved these changes
大きな問題などがありません。よくできていると思います。

一つ気になった点ですが、「Unit test passed」とかなり書いていたが、このプロジェクトはユニットテストがありましたか？

2023-09-14 14:30 UTC, Zudies commented on Assets/Scripts/QualiaIntensity.cs
> +    // so may have to be managed by ScriptableObject or other ways.
はい、すでにPlayerManagerで管理しています。

2023-09-22 06:41 UTC, LosenkaNiya commented
メソッド単位での入出力チェックを行ったときにメモしていたものです

2023-09-22 06:41 UTC, merged