YellowAnimaBehavior実装
kmc-jp/puzzleGame2023 pull request #72
Opened 2023-09-05 07:45 UTC by OsawaKousei

gravityScaleを0にして、宙に浮くようにしてあります。
massはAoutoMassを使用しています。

2023-09-05 15:19 UTC, LosenkaNiya commented on Assets/Scripts/YellowAnimaMovementBehavior.cs
> +using System.Collections.Generic;
```suggestion
```

これは単なる好みの問題なので大した話じゃないですが、使わないusingは消しておくとどのコードが参照しているかがわかりやすくなるのでおすすめです。

2023-09-05 15:25 UTC, LosenkaNiya requested changes
現状の実装としては問題ありません。ただ、パラメータを調整したりするためにはある程度完成してからテストしないといけないので、その場合はSerializeFieldやScriptableObjectを使ってパラメータを外部に公開する必要が出てくるかもしれません。

主力プログラマなので、細かいですが気になるところをレビューしました。修正だけお願いします。

2023-09-07 12:17 UTC, LosenkaNiya approved these changes
対応ありがとうございました。クローズしてmainにプルしてください。

2023-09-08 14:56 UTC, Zudies commented
#66をマージしましたため、このブランチにコンフリクトが出ています。GMforTest01がなくなったけど、カラー変更の機能はすでに実装しましたのでこのYellowAnimaBehaviorとテストオブジェクトのみマージしましょう。

2023-09-23 10:57 UTC, Zudies approved these changes

2023-10-09 08:34 UTC, merged